In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel('credit_card_data.xls')

In [3]:
df.head()

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE PAY_1  PAY_2  \
0  798fc410-45c1      20000    2          2         1   24     2      2   
1  8a8c8f3b-8eb4     120000    2          2         2   26    -1      2   
2  85698822-43f5      90000    2          2         2   34     0      0   
3  0737c11b-be42      50000    2          2         1   37     0      0   
4  3b7f77cc-dbc0      50000    1          2         1   57    -1      0   

   PAY_3  PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0     -1     -1  ...          0          0          0         0       689   
1      0      0  ...       3272       3455       3261         0      1000   
2      0      0  ...      14331      14948      15549      1518      1500   
3      0      0  ...      28314      28959      29547      2000      2019   
4     -1      0  ...      20940      19146      19131      2000     36681   

   PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
0         0         0         0         0                           1  
1      1000      1000         0      2000                           1  
2      1000      1000      1000      5000                           0  
3      1200      1100      1069      1000                           0  
4     10000      9000       689       679                           0  

[5 rows x 25 columns]

In [4]:
df.columns

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_1',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default payment next month'],
      dtype='object')

In [5]:
# Which of these are numerical? Which are categorical?
# Look on page 21 for more details on the 
# specific information about each column

In [6]:
df.shape

(30000, 25)

In [7]:
df['MARRIAGE'] # look at different variables

0        1
1        2
2        2
3        1
4        1
        ..
29995    1
29996    2
29997    2
29998    1
29999    1
Name: MARRIAGE, Length: 30000, dtype: int64

In [8]:
df['ID'].shape

(30000,)

In [9]:
df['ID'].nunique()

29687

In [10]:
# the number of unique IDs is less than the number of rows
# How do we figure out which IDs are duplicated? 
# Is it several, or just one repeated multiple times?

id_counts = df['ID'].value_counts()
id_counts.head()

9611f432-7f70    2
3cfed539-ad58    2
06f377a6-ba7e    2
8b62a9c9-7b64    2
369e565a-26a1    2
Name: ID, dtype: int64

In [11]:
# that gives us which values are duplicated
# but how do we figure out how many are duplicated?
# any ideas?

id_counts.value_counts()

1    29374
2      313
Name: ID, dtype: int64

In [12]:
# back to slides about boolean masks

In [13]:
# first let's just understand boolean masks using synthetic data
random_integers = np.random.randint(low=1,high=5,size=100)
random_integers

array([2, 1, 2, 2, 1, 3, 3, 3, 2, 4, 2, 3, 4, 2, 1, 3, 2, 3, 3, 3, 2, 3,
       2, 1, 2, 2, 1, 2, 4, 4, 3, 2, 4, 3, 4, 4, 1, 3, 2, 4, 3, 4, 4, 3,
       1, 3, 4, 4, 3, 3, 1, 3, 2, 2, 2, 4, 1, 3, 2, 3, 3, 2, 3, 1, 4, 2,
       3, 2, 3, 3, 4, 4, 3, 1, 1, 4, 2, 4, 2, 3, 3, 2, 4, 3, 1, 1, 2, 4,
       4, 2, 4, 2, 2, 2, 1, 3, 4, 1, 2, 2])

In [14]:
is_equal_to_3 = random_integers == 3
is_equal_to_3

array([False, False, False, False, False,  True,  True,  True, False,
       False, False,  True, False, False, False,  True, False,  True,
        True,  True, False,  True, False, False, False, False, False,
       False, False, False,  True, False, False,  True, False, False,
       False,  True, False, False,  True, False, False,  True, False,
        True, False, False,  True,  True, False,  True, False, False,
       False, False, False,  True, False,  True,  True, False,  True,
       False, False, False,  True, False,  True,  True, False, False,
        True, False, False, False, False, False, False,  True,  True,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False])

In [15]:
sum(is_equal_to_3)

30

In [16]:
random_integers[is_equal_to_3]

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3])

In [17]:
dupe_mask = id_counts == 2
dupe_mask[:5]

9611f432-7f70    True
3cfed539-ad58    True
06f377a6-ba7e    True
8b62a9c9-7b64    True
369e565a-26a1    True
Name: ID, dtype: bool

In [18]:
id_counts.index[:5]

Index(['9611f432-7f70', '3cfed539-ad58', '06f377a6-ba7e', '8b62a9c9-7b64',
       '369e565a-26a1'],
      dtype='object')

In [19]:
dupe_ids = id_counts.index[dupe_mask]
dupe_ids = list(dupe_ids)
len(dupe_ids)

313

In [20]:
dupe_of_first_ids = df['ID'].isin(dupe_ids[:3])
dupe_of_first_ids

0        False
1        False
2        False
3        False
4        False
         ...  
29995    False
29996    False
29997    False
29998    False
29999    False
Name: ID, Length: 30000, dtype: bool

In [21]:
df.loc[dupe_of_first_ids,:]

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE          PAY_1  \
5006   9611f432-7f70     280000    2          1         2   31  Not available   
5106   9611f432-7f70          0    0          0         0    0              0   
10294  3cfed539-ad58     180000    2          3         2   29             -2   
10394  3cfed539-ad58          0    0          0         0    0              0   
25421  06f377a6-ba7e      30000    2          1         2   22             -1   
25521  06f377a6-ba7e          0    0          0         0    0              0   

       PAY_2  PAY_3  PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  \
5006      -2     -2     -2  ...        326        652          0       326   
5106       0      0      0  ...          0          0          0         0   
10294     -2     -2     -2  ...          0          0          0         0   
10394      0      0      0  ...          0          0          0         0   
25421     -1     -1     -1  ...        182          0          0      3173   
25521      0      0      0  ...          0          0          0         0   

       PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  \
5006          0       326       652         0       652   
5106          0         0         0         0         0   
10294         0         0         0         0         0   
10394         0         0         0         0         0   
25421      1972       183         0         0       440   
25521         0         0         0         0         0   

       default payment next month  
5006                            0  
5106                            0  
10294                           0  
10394                           0  
25421                           0  
25521                           0  

[6 rows x 25 columns]

In [22]:
# okay, so it looks like there's one row w/ data and one row w/ all zeros
# what should we do?

In [23]:
# Find all of the places where our dataframe has zero values
df_zero_mask = df == 0

# find all of the rows where the elements starting from 
# the _second_ column are 0 (the IDs won't be 0 no matter what)
# .loc gets the locations that are true
# .iloc gets the locations specified by specific integer indices
data_without_ids = df_zero_mask.iloc[:,1:]

# use .all(axis=1) to return true if every element in the row is true
whole_row_zero = data_without_ids.all(axis=1) 
sum(whole_row_zero)

315

In [24]:
# create a *new* dataframe w/ the de-duplicated data
good_rows = ~whole_row_zero
df_clean_1 = df.loc[good_rows,:].copy() # without the 'copy' this would just create a 'view'

In [25]:
df_clean_1.shape

(29685, 25)

In [26]:
df_clean_1['ID'].nunique()

29685

In [27]:
df_clean_1.info()
# just because this says 'non-null' doesn't mean
# that there isn't some place holder for 'no info'

<class 'pandas.core.frame.DataFrame'>
Int64Index: 29685 entries, 0 to 29999
Data columns (total 25 columns):
ID                            29685 non-null object
LIMIT_BAL                     29685 non-null int64
SEX                           29685 non-null int64
EDUCATION                     29685 non-null int64
MARRIAGE                      29685 non-null int64
AGE                           29685 non-null int64
PAY_1                         29685 non-null object
PAY_2                         29685 non-null int64
PAY_3                         29685 non-null int64
PAY_4                         29685 non-null int64
PAY_5                         29685 non-null int64
PAY_6                         29685 non-null int64
BILL_AMT1                     29685 non-null int64
BILL_AMT2                     29685 non-null int64
BILL_AMT3                     29685 non-null int64
BILL_AMT4                     29685 non-null int64
BILL_AMT5                     29685 non-null int64
BILL_AMT6             

In [28]:
# why does PAY_1 not say integer??
df_clean_1['PAY_1'].head(5) # those all look like integers...

0     2
1    -1
2     0
3     0
4    -1
Name: PAY_1, dtype: object

In [29]:
df_clean_1['PAY_1'].value_counts()

0                13087
-1                5047
1                 3261
Not available     3021
-2                2476
2                 2378
3                  292
4                   63
5                   23
8                   17
6                   11
7                    9
Name: PAY_1, dtype: int64

In [ ]:
# Your job: remove the rows that have 
# 'Not available' PAY_1 data in them
# and save that cleaned data out to a new data frame, df_clean_2